// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy2MuP-JGTK3dnzq4-OaJZ65qj-r64Jik',
    appId: '1:376562390271:web:fc0e55ea0b548743e5e8ca',
    messagingSenderId: '376562390271',
    projectId: 'coffeshop-2876d',
    authDomain: 'coffeshop-2876d.firebaseapp.com',
    databaseURL: 'https://coffeshop-2876d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffeshop-2876d.firebasestorage.app',
    measurementId: 'G-1KMK6WKYTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Msqp22IHLJHzhWsrzZnmt-0oEIgwogo',
    appId: '1:376562390271:android:032a3b44185584c5e5e8ca',
    messagingSenderId: '376562390271',
    projectId: 'coffeshop-2876d',
    databaseURL: 'https://coffeshop-2876d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffeshop-2876d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQMmsTLsbViLfqFIebwtPSku90klBoFF8',
    appId: '1:376562390271:ios:dbe3028ac8d36d18e5e8ca',
    messagingSenderId: '376562390271',
    projectId: 'coffeshop-2876d',
    databaseURL: 'https://coffeshop-2876d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffeshop-2876d.firebasestorage.app',
    iosClientId: '376562390271-o84iiiguaskgs0o3s6m4uko3kah94muv.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQMmsTLsbViLfqFIebwtPSku90klBoFF8',
    appId: '1:376562390271:ios:dbe3028ac8d36d18e5e8ca',
    messagingSenderId: '376562390271',
    projectId: 'coffeshop-2876d',
    databaseURL: 'https://coffeshop-2876d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffeshop-2876d.firebasestorage.app',
    iosClientId: '376562390271-o84iiiguaskgs0o3s6m4uko3kah94muv.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy2MuP-JGTK3dnzq4-OaJZ65qj-r64Jik',
    appId: '1:376562390271:web:f7a5afb68519b40ee5e8ca',
    messagingSenderId: '376562390271',
    projectId: 'coffeshop-2876d',
    authDomain: 'coffeshop-2876d.firebaseapp.com',
    databaseURL: 'https://coffeshop-2876d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffeshop-2876d.firebasestorage.app',
    measurementId: 'G-Y9W8HJE5J8',
  );
}
